[package]
name = "JavaLauncher"
version = "0.2.1"
authors = ["Kevin Eastridge"]
edition = "2021"
license = "LGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# See https://github.com/jni-rs/jni-rs/pull/293 linking to path only is silly
jni = { git = "https://github.com/keastrid/jni-rs", branch = "dyn-load-jvm", features = ["invocation", "invocation-dyn"] }
walkdir = "2"
config = "0.12.0"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

# From https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # instructs the linker to optimize at the link stage. This can, for example, remove dead code and often times reduces binary size.
codegen-units = 1 # Slower, but more optimization?
panic = "abort" # No helpful stacktrace on panic