name: Release Launcher

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    env:
      SDKVERSION: 15.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: '0.13.0'

      - name: Install zigbuild
        run: |
          cargo install --locked cargo-zigbuild

      - name: Install targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: Setup SDK for mac
        run: |
          set -e
          curl -sqL "https://github.com/joseluisq/macosx-sdks/releases/download/$SDKVERSION/MacOSX$SDKVERSION.sdk.tar.xz" | tar -J -x -C /opt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 binutils-mingw-w64-x86-64

      - name: Build
        run: |
          cargo zigbuild --target x86_64-unknown-linux-gnu --release
          cargo zigbuild --target x86_64-pc-windows-gnu --release
          SDKROOT="/opt/MacOSX$SDKVERSION.sdk" cargo zigbuild --target universal2-apple-darwin --release
          SDKROOT="/opt/MacOSX$SDKVERSION.sdk" cargo zigbuild --target x86_64-apple-darwin --release
          SDKROOT="/opt/MacOSX$SDKVERSION.sdk" cargo zigbuild --target aarch64-apple-darwin --release

      # Upload artifacts
      - name: Upload x86_64-unknown-linux-gnu
        uses: actions/upload-artifact@v4
        with:
          name: JavaLauncher-x86_64-unknown-linux-gnu
          if-no-files-found: error
          path: |
            target/x86_64-unknown-linux-gnu/release/JavaLauncher
      - name: Upload x86_64-pc-windows-gnu
        uses: actions/upload-artifact@v4
        with:
          name: JavaLauncher-x86_64-pc-windows-gnu
          if-no-files-found: error
          path: |
            target/x86_64-pc-windows-gnu/release/JavaLauncher.exe
      - name: Upload universal2-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: JavaLauncher-universal2-apple-darwin
          if-no-files-found: error
          path: |
            target/universal2-apple-darwin/release/JavaLauncher
      - name: Upload x86_64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: JavaLauncher-x86_64-apple-darwin
          if-no-files-found: error
          path: |
            target/x86_64-apple-darwin/release/JavaLauncher
      - name: Upload aarch64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: JavaLauncher-aarch64-apple-darwin
          if-no-files-found: error
          path: |
            target/aarch64-apple-darwin/release/JavaLauncher